Repository facebookresearch/mbrl-lib, pull requests merged in 2021-07, with the labels that each got.

#100 Fixed the condition of the warning in ReplayBuffer.close_trajectory()
  mbrl/util/replay_buffer.py
Labels: CLA Signed

#103 [bug-fix] Fixed bug in code to keep best weights during model trainin…
  mbrl/models/model_trainer.py
Labels: CLA Signed

#104 Bugfix in ModelTrainer.maybe_get_best_weights() and made the threshold for improvement configurable from ModelTrainer.train()
  mbrl/models/model_trainer.py
  mbrl/util/common.py
  tests/core/test_common_utils.py
Labels: CLA Signed

#105 Fixed a bug where SequenceTransitionIterator.__len__() ignores max_batches_per_loop
  mbrl/util/replay_buffer.py
  tests/core/test_replay_buffer.py
Labels: CLA Signed

#106 Fixed a bug where a default argument to get_sequence_buffer_iterator causes a crash and added an assertion for clarity
  mbrl/util/common.py
Labels: CLA Signed

#91 Added sequence iterator
  CHANGELOG.md
  mbrl/__init__.py
  mbrl/diagnostics/eval_model_on_dataset.py
  mbrl/diagnostics/finetune_model_with_controller.py
  mbrl/types.py
  mbrl/util/__init__.py
  mbrl/util/common.py
  mbrl/util/replay_buffer.py
  notebooks/pets_example.ipynb
  tests/core/test_common_utils.py
  tests/core/test_replay_buffer.py
Labels: CLA Signed, enhancement

#107 Fixed some type hints of ReplayBuffer
  mbrl/util/common.py
  mbrl/util/replay_buffer.py
Labels: CLA Signed

#109 Model functions now include metadata
  mbrl/models/basic_ensemble.py
  mbrl/models/gaussian_mlp.py
  mbrl/models/model.py
  mbrl/models/model_trainer.py
  mbrl/models/one_dim_tr_model.py
  notebooks/fit_gaussian_mlp_ensemble_1d.ipynb
  tests/core/test_models.py
Labels: CLA Signed, enhancement

#111 Add option to do normalization using double precision for 1-D models
  CHANGELOG.md
  mbrl/__init__.py
  mbrl/algorithms/mbpo.py
  mbrl/algorithms/pets.py
  mbrl/diagnostics/finetune_model_with_controller.py
  mbrl/examples/conf/algorithm/mbpo.yaml
  mbrl/examples/conf/algorithm/pets.yaml
  mbrl/models/one_dim_tr_model.py
  mbrl/util/common.py
  mbrl/util/math.py
  mbrl/util/replay_buffer.py
  tests/core/test_common_utils.py
Labels: CLA Signed, bug, enhancement
